// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: v_architect_core.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VirtualHardwareArch int32

const (
	VirtualHardwareArch_ARCH_UNSPECIFIED VirtualHardwareArch = 0
	VirtualHardwareArch_X86_64           VirtualHardwareArch = 1
	VirtualHardwareArch_ARM64            VirtualHardwareArch = 2
)

// Enum value maps for VirtualHardwareArch.
var (
	VirtualHardwareArch_name = map[int32]string{
		0: "ARCH_UNSPECIFIED",
		1: "X86_64",
		2: "ARM64",
	}
	VirtualHardwareArch_value = map[string]int32{
		"ARCH_UNSPECIFIED": 0,
		"X86_64":           1,
		"ARM64":            2,
	}
)

func (x VirtualHardwareArch) Enum() *VirtualHardwareArch {
	p := new(VirtualHardwareArch)
	*p = x
	return p
}

func (x VirtualHardwareArch) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VirtualHardwareArch) Descriptor() protoreflect.EnumDescriptor {
	return file_v_architect_core_proto_enumTypes[0].Descriptor()
}

func (VirtualHardwareArch) Type() protoreflect.EnumType {
	return &file_v_architect_core_proto_enumTypes[0]
}

func (x VirtualHardwareArch) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VirtualHardwareArch.Descriptor instead.
func (VirtualHardwareArch) EnumDescriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{0}
}

type SerialPortConfig_SerialPortType int32

const (
	SerialPortConfig_SERIAL_TYPE_UNSPECIFIED SerialPortConfig_SerialPortType = 0
	SerialPortConfig_LOG_ONLY                SerialPortConfig_SerialPortType = 1 // Conceptual: Logs to VMM log, no host device
	SerialPortConfig_STDIO                   SerialPortConfig_SerialPortType = 2 // Connect to VMM's stdio streams
	SerialPortConfig_FILE                    SerialPortConfig_SerialPortType = 3 // Output to/input from a host file
	SerialPortConfig_PTY                     SerialPortConfig_SerialPortType = 4 // Use a pseudo-terminal on the host
	SerialPortConfig_TCP_SOCKET_SERVER       SerialPortConfig_SerialPortType = 5
	SerialPortConfig_TCP_SOCKET_CLIENT       SerialPortConfig_SerialPortType = 6
	SerialPortConfig_NAMED_PIPE              SerialPortConfig_SerialPortType = 7
	SerialPortConfig_NONE                    SerialPortConfig_SerialPortType = 8 // Explicitly no device
)

// Enum value maps for SerialPortConfig_SerialPortType.
var (
	SerialPortConfig_SerialPortType_name = map[int32]string{
		0: "SERIAL_TYPE_UNSPECIFIED",
		1: "LOG_ONLY",
		2: "STDIO",
		3: "FILE",
		4: "PTY",
		5: "TCP_SOCKET_SERVER",
		6: "TCP_SOCKET_CLIENT",
		7: "NAMED_PIPE",
		8: "NONE",
	}
	SerialPortConfig_SerialPortType_value = map[string]int32{
		"SERIAL_TYPE_UNSPECIFIED": 0,
		"LOG_ONLY":                1,
		"STDIO":                   2,
		"FILE":                    3,
		"PTY":                     4,
		"TCP_SOCKET_SERVER":       5,
		"TCP_SOCKET_CLIENT":       6,
		"NAMED_PIPE":              7,
		"NONE":                    8,
	}
)

func (x SerialPortConfig_SerialPortType) Enum() *SerialPortConfig_SerialPortType {
	p := new(SerialPortConfig_SerialPortType)
	*p = x
	return p
}

func (x SerialPortConfig_SerialPortType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SerialPortConfig_SerialPortType) Descriptor() protoreflect.EnumDescriptor {
	return file_v_architect_core_proto_enumTypes[1].Descriptor()
}

func (SerialPortConfig_SerialPortType) Type() protoreflect.EnumType {
	return &file_v_architect_core_proto_enumTypes[1]
}

func (x SerialPortConfig_SerialPortType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SerialPortConfig_SerialPortType.Descriptor instead.
func (SerialPortConfig_SerialPortType) EnumDescriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{2, 0}
}

type GraphicsConfig_GraphicsType int32

const (
	GraphicsConfig_GRAPHICS_TYPE_UNSPECIFIED GraphicsConfig_GraphicsType = 0
	GraphicsConfig_NONE                      GraphicsConfig_GraphicsType = 1
	GraphicsConfig_VGA_COMPATIBLE            GraphicsConfig_GraphicsType = 2
	GraphicsConfig_VIRTIO_GPU                GraphicsConfig_GraphicsType = 3
	GraphicsConfig_GPU_PASSTHROUGH           GraphicsConfig_GraphicsType = 4
	GraphicsConfig_MEDIATED_VGPU             GraphicsConfig_GraphicsType = 5
)

// Enum value maps for GraphicsConfig_GraphicsType.
var (
	GraphicsConfig_GraphicsType_name = map[int32]string{
		0: "GRAPHICS_TYPE_UNSPECIFIED",
		1: "NONE",
		2: "VGA_COMPATIBLE",
		3: "VIRTIO_GPU",
		4: "GPU_PASSTHROUGH",
		5: "MEDIATED_VGPU",
	}
	GraphicsConfig_GraphicsType_value = map[string]int32{
		"GRAPHICS_TYPE_UNSPECIFIED": 0,
		"NONE":                      1,
		"VGA_COMPATIBLE":            2,
		"VIRTIO_GPU":                3,
		"GPU_PASSTHROUGH":           4,
		"MEDIATED_VGPU":             5,
	}
)

func (x GraphicsConfig_GraphicsType) Enum() *GraphicsConfig_GraphicsType {
	p := new(GraphicsConfig_GraphicsType)
	*p = x
	return p
}

func (x GraphicsConfig_GraphicsType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GraphicsConfig_GraphicsType) Descriptor() protoreflect.EnumDescriptor {
	return file_v_architect_core_proto_enumTypes[2].Descriptor()
}

func (GraphicsConfig_GraphicsType) Type() protoreflect.EnumType {
	return &file_v_architect_core_proto_enumTypes[2]
}

func (x GraphicsConfig_GraphicsType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GraphicsConfig_GraphicsType.Descriptor instead.
func (GraphicsConfig_GraphicsType) EnumDescriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{6, 0}
}

type VMConfig_FirmwareType int32

const (
	VMConfig_FIRMWARE_TYPE_UNSPECIFIED VMConfig_FirmwareType = 0
	VMConfig_BIOS                      VMConfig_FirmwareType = 1
	VMConfig_UEFI                      VMConfig_FirmwareType = 2
)

// Enum value maps for VMConfig_FirmwareType.
var (
	VMConfig_FirmwareType_name = map[int32]string{
		0: "FIRMWARE_TYPE_UNSPECIFIED",
		1: "BIOS",
		2: "UEFI",
	}
	VMConfig_FirmwareType_value = map[string]int32{
		"FIRMWARE_TYPE_UNSPECIFIED": 0,
		"BIOS":                      1,
		"UEFI":                      2,
	}
)

func (x VMConfig_FirmwareType) Enum() *VMConfig_FirmwareType {
	p := new(VMConfig_FirmwareType)
	*p = x
	return p
}

func (x VMConfig_FirmwareType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VMConfig_FirmwareType) Descriptor() protoreflect.EnumDescriptor {
	return file_v_architect_core_proto_enumTypes[3].Descriptor()
}

func (VMConfig_FirmwareType) Type() protoreflect.EnumType {
	return &file_v_architect_core_proto_enumTypes[3]
}

func (x VMConfig_FirmwareType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VMConfig_FirmwareType.Descriptor instead.
func (VMConfig_FirmwareType) EnumDescriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{8, 0}
}

type HealthCheckResponse_Status int32

const (
	HealthCheckResponse_UNKNOWN   HealthCheckResponse_Status = 0
	HealthCheckResponse_HEALTHY   HealthCheckResponse_Status = 1
	HealthCheckResponse_DEGRADED  HealthCheckResponse_Status = 2
	HealthCheckResponse_UNHEALTHY HealthCheckResponse_Status = 3
)

// Enum value maps for HealthCheckResponse_Status.
var (
	HealthCheckResponse_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "HEALTHY",
		2: "DEGRADED",
		3: "UNHEALTHY",
	}
	HealthCheckResponse_Status_value = map[string]int32{
		"UNKNOWN":   0,
		"HEALTHY":   1,
		"DEGRADED":  2,
		"UNHEALTHY": 3,
	}
)

func (x HealthCheckResponse_Status) Enum() *HealthCheckResponse_Status {
	p := new(HealthCheckResponse_Status)
	*p = x
	return p
}

func (x HealthCheckResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_v_architect_core_proto_enumTypes[4].Descriptor()
}

func (HealthCheckResponse_Status) Type() protoreflect.EnumType {
	return &file_v_architect_core_proto_enumTypes[4]
}

func (x HealthCheckResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_Status.Descriptor instead.
func (HealthCheckResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{18, 0}
}

type DiskImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	ReadOnly      bool                   `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"` // string disk_id = 4; // Re-adding disk_id as it's useful for boot_order
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskImage) Reset() {
	*x = DiskImage{}
	mi := &file_v_architect_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskImage) ProtoMessage() {}

func (x *DiskImage) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskImage.ProtoReflect.Descriptor instead.
func (*DiskImage) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{0}
}

func (x *DiskImage) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DiskImage) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *DiskImage) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

type NetworkInterface struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NicId         string                 `protobuf:"bytes,1,opt,name=nic_id,json=nicId,proto3" json:"nic_id,omitempty"` // Unique within the VM, e.g., "net0"
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                // e.g., "virtio-net" (model)
	MacAddress    string                 `protobuf:"bytes,3,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	BridgeName    string                 `protobuf:"bytes,4,opt,name=bridge_name,json=bridgeName,proto3" json:"bridge_name,omitempty"` // Host bridge to attach to, or network name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInterface) Reset() {
	*x = NetworkInterface{}
	mi := &file_v_architect_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInterface) ProtoMessage() {}

func (x *NetworkInterface) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInterface.ProtoReflect.Descriptor instead.
func (*NetworkInterface) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{1}
}

func (x *NetworkInterface) GetNicId() string {
	if x != nil {
		return x.NicId
	}
	return ""
}

func (x *NetworkInterface) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NetworkInterface) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *NetworkInterface) GetBridgeName() string {
	if x != nil {
		return x.BridgeName
	}
	return ""
}

type SerialPortConfig struct {
	state          protoimpl.MessageState          `protogen:"open.v1"`
	Id             string                          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // e.g., "serial0", "com1"
	Type           SerialPortConfig_SerialPortType `protobuf:"varint,2,opt,name=type,proto3,enum=proto.SerialPortConfig_SerialPortType" json:"type,omitempty"`
	PathOrAddress  string                          `protobuf:"bytes,3,opt,name=path_or_address,json=pathOrAddress,proto3" json:"path_or_address,omitempty"`     // Path for FILE/PTY/NAMED_PIPE, "host:port" for TCP
	IoBaseOverride uint32                          `protobuf:"varint,4,opt,name=io_base_override,json=ioBaseOverride,proto3" json:"io_base_override,omitempty"` // Optional: Override default I/O port (e.g., 0x3F8)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SerialPortConfig) Reset() {
	*x = SerialPortConfig{}
	mi := &file_v_architect_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerialPortConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerialPortConfig) ProtoMessage() {}

func (x *SerialPortConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerialPortConfig.ProtoReflect.Descriptor instead.
func (*SerialPortConfig) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{2}
}

func (x *SerialPortConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SerialPortConfig) GetType() SerialPortConfig_SerialPortType {
	if x != nil {
		return x.Type
	}
	return SerialPortConfig_SERIAL_TYPE_UNSPECIFIED
}

func (x *SerialPortConfig) GetPathOrAddress() string {
	if x != nil {
		return x.PathOrAddress
	}
	return ""
}

func (x *SerialPortConfig) GetIoBaseOverride() uint32 {
	if x != nil {
		return x.IoBaseOverride
	}
	return 0
}

type VCPUConfig struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	EnableKvmHv         bool                   `protobuf:"varint,1,opt,name=enable_kvm_hv,json=enableKvmHv,proto3" json:"enable_kvm_hv,omitempty"`
	Count               uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"` // Moved from VMConfig top level for clarity
	Topology            *VCPUConfig_Topology   `protobuf:"bytes,3,opt,name=topology,proto3" json:"topology,omitempty"`
	CpuFeaturesToEnable []string               `protobuf:"bytes,4,rep,name=cpu_features_to_enable,json=cpuFeaturesToEnable,proto3" json:"cpu_features_to_enable,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *VCPUConfig) Reset() {
	*x = VCPUConfig{}
	mi := &file_v_architect_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VCPUConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VCPUConfig) ProtoMessage() {}

func (x *VCPUConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VCPUConfig.ProtoReflect.Descriptor instead.
func (*VCPUConfig) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{3}
}

func (x *VCPUConfig) GetEnableKvmHv() bool {
	if x != nil {
		return x.EnableKvmHv
	}
	return false
}

func (x *VCPUConfig) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *VCPUConfig) GetTopology() *VCPUConfig_Topology {
	if x != nil {
		return x.Topology
	}
	return nil
}

func (x *VCPUConfig) GetCpuFeaturesToEnable() []string {
	if x != nil {
		return x.CpuFeaturesToEnable
	}
	return nil
}

type MemoryConfig struct {
	state               protoimpl.MessageState         `protogen:"open.v1"`
	SizeMb              uint64                         `protobuf:"varint,1,opt,name=size_mb,json=sizeMb,proto3" json:"size_mb,omitempty"` // Moved from VMConfig top level
	EnableHugePages     bool                           `protobuf:"varint,2,opt,name=enable_huge_pages,json=enableHugePages,proto3" json:"enable_huge_pages,omitempty"`
	EnableMemBallooning bool                           `protobuf:"varint,3,opt,name=enable_mem_ballooning,json=enableMemBallooning,proto3" json:"enable_mem_ballooning,omitempty"`
	AiOptimizedFlags    *MemoryConfig_AIOptimizedFlags `protobuf:"bytes,4,opt,name=ai_optimized_flags,json=aiOptimizedFlags,proto3" json:"ai_optimized_flags,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MemoryConfig) Reset() {
	*x = MemoryConfig{}
	mi := &file_v_architect_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryConfig) ProtoMessage() {}

func (x *MemoryConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryConfig.ProtoReflect.Descriptor instead.
func (*MemoryConfig) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{4}
}

func (x *MemoryConfig) GetSizeMb() uint64 {
	if x != nil {
		return x.SizeMb
	}
	return 0
}

func (x *MemoryConfig) GetEnableHugePages() bool {
	if x != nil {
		return x.EnableHugePages
	}
	return false
}

func (x *MemoryConfig) GetEnableMemBallooning() bool {
	if x != nil {
		return x.EnableMemBallooning
	}
	return false
}

func (x *MemoryConfig) GetAiOptimizedFlags() *MemoryConfig_AIOptimizedFlags {
	if x != nil {
		return x.AiOptimizedFlags
	}
	return nil
}

type AIHardwareConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnableAiCpu   bool                   `protobuf:"varint,1,opt,name=enable_ai_cpu,json=enableAiCpu,proto3" json:"enable_ai_cpu,omitempty"`
	EnableAiGpu   bool                   `protobuf:"varint,2,opt,name=enable_ai_gpu,json=enableAiGpu,proto3" json:"enable_ai_gpu,omitempty"` // More detailed AICPUConfig and AIGraphicsCardConfig can be added later
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIHardwareConfig) Reset() {
	*x = AIHardwareConfig{}
	mi := &file_v_architect_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIHardwareConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIHardwareConfig) ProtoMessage() {}

func (x *AIHardwareConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIHardwareConfig.ProtoReflect.Descriptor instead.
func (*AIHardwareConfig) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{5}
}

func (x *AIHardwareConfig) GetEnableAiCpu() bool {
	if x != nil {
		return x.EnableAiCpu
	}
	return false
}

func (x *AIHardwareConfig) GetEnableAiGpu() bool {
	if x != nil {
		return x.EnableAiGpu
	}
	return false
}

type GraphicsConfig struct {
	state                   protoimpl.MessageState      `protogen:"open.v1"`
	Type                    GraphicsConfig_GraphicsType `protobuf:"varint,1,opt,name=type,proto3,enum=proto.GraphicsConfig_GraphicsType" json:"type,omitempty"`
	VgpuProfileOrPhysicalId string                      `protobuf:"bytes,2,opt,name=vgpu_profile_or_physical_id,json=vgpuProfileOrPhysicalId,proto3" json:"vgpu_profile_or_physical_id,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GraphicsConfig) Reset() {
	*x = GraphicsConfig{}
	mi := &file_v_architect_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphicsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphicsConfig) ProtoMessage() {}

func (x *GraphicsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphicsConfig.ProtoReflect.Descriptor instead.
func (*GraphicsConfig) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{6}
}

func (x *GraphicsConfig) GetType() GraphicsConfig_GraphicsType {
	if x != nil {
		return x.Type
	}
	return GraphicsConfig_GRAPHICS_TYPE_UNSPECIFIED
}

func (x *GraphicsConfig) GetVgpuProfileOrPhysicalId() string {
	if x != nil {
		return x.VgpuProfileOrPhysicalId
	}
	return ""
}

type PCIPassthroughDevice struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HostPciAddress string                 `protobuf:"bytes,1,opt,name=host_pci_address,json=hostPciAddress,proto3" json:"host_pci_address,omitempty"`
	IommuGroupPath string                 `protobuf:"bytes,2,opt,name=iommu_group_path,json=iommuGroupPath,proto3" json:"iommu_group_path,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PCIPassthroughDevice) Reset() {
	*x = PCIPassthroughDevice{}
	mi := &file_v_architect_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PCIPassthroughDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PCIPassthroughDevice) ProtoMessage() {}

func (x *PCIPassthroughDevice) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PCIPassthroughDevice.ProtoReflect.Descriptor instead.
func (*PCIPassthroughDevice) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{7}
}

func (x *PCIPassthroughDevice) GetHostPciAddress() string {
	if x != nil {
		return x.HostPciAddress
	}
	return ""
}

func (x *PCIPassthroughDevice) GetIommuGroupPath() string {
	if x != nil {
		return x.IommuGroupPath
	}
	return ""
}

// Main VM Configuration message
type VMConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	VmId              string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DiskImages        []*DiskImage           `protobuf:"bytes,5,rep,name=disk_images,json=diskImages,proto3" json:"disk_images,omitempty"`
	NetworkInterfaces []*NetworkInterface    `protobuf:"bytes,6,rep,name=network_interfaces,json=networkInterfaces,proto3" json:"network_interfaces,omitempty"`
	SerialPorts       []*SerialPortConfig    `protobuf:"bytes,7,rep,name=serial_ports,json=serialPorts,proto3" json:"serial_ports,omitempty"`
	// bool enable_bios_boot = 8;   // Replaced by firmware_type
	KernelImagePath       string                  `protobuf:"bytes,9,opt,name=kernel_image_path,json=kernelImagePath,proto3" json:"kernel_image_path,omitempty"`
	InitrdPath            string                  `protobuf:"bytes,10,opt,name=initrd_path,json=initrdPath,proto3" json:"initrd_path,omitempty"`
	KernelCmdline         string                  `protobuf:"bytes,11,opt,name=kernel_cmdline,json=kernelCmdline,proto3" json:"kernel_cmdline,omitempty"`
	Arch                  VirtualHardwareArch     `protobuf:"varint,12,opt,name=arch,proto3,enum=proto.VirtualHardwareArch" json:"arch,omitempty"`
	VcpuConfig            *VCPUConfig             `protobuf:"bytes,13,opt,name=vcpu_config,json=vcpuConfig,proto3" json:"vcpu_config,omitempty"`       // Now includes count
	MemoryConfig          *MemoryConfig           `protobuf:"bytes,14,opt,name=memory_config,json=memoryConfig,proto3" json:"memory_config,omitempty"` // Now includes size_mb
	AiHardwareConfig      *AIHardwareConfig       `protobuf:"bytes,15,opt,name=ai_hardware_config,json=aiHardwareConfig,proto3" json:"ai_hardware_config,omitempty"`
	GraphicsConfig        *GraphicsConfig         `protobuf:"bytes,19,opt,name=graphics_config,json=graphicsConfig,proto3" json:"graphics_config,omitempty"` // Number changed to avoid collision if fields were added and removed
	Metadata              map[string]string       `protobuf:"bytes,16,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BootOrder             []string                `protobuf:"bytes,20,rep,name=boot_order,json=bootOrder,proto3" json:"boot_order,omitempty"` // List of DiskImage.disk_id or NetworkInterface.nic_id
	FirmwareType          VMConfig_FirmwareType   `protobuf:"varint,21,opt,name=firmware_type,json=firmwareType,proto3,enum=proto.VMConfig_FirmwareType" json:"firmware_type,omitempty"`
	SecureBootEnabled     bool                    `protobuf:"varint,22,opt,name=secure_boot_enabled,json=secureBootEnabled,proto3" json:"secure_boot_enabled,omitempty"`
	VirtualTpmEnabled     bool                    `protobuf:"varint,23,opt,name=virtual_tpm_enabled,json=virtualTpmEnabled,proto3" json:"virtual_tpm_enabled,omitempty"`
	PciPassthroughDevices []*PCIPassthroughDevice `protobuf:"bytes,24,rep,name=pci_passthrough_devices,json=pciPassthroughDevices,proto3" json:"pci_passthrough_devices,omitempty"` // AIAcceleratedHardware from finalized proto would go here too.
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *VMConfig) Reset() {
	*x = VMConfig{}
	mi := &file_v_architect_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMConfig) ProtoMessage() {}

func (x *VMConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMConfig.ProtoReflect.Descriptor instead.
func (*VMConfig) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{8}
}

func (x *VMConfig) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *VMConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VMConfig) GetDiskImages() []*DiskImage {
	if x != nil {
		return x.DiskImages
	}
	return nil
}

func (x *VMConfig) GetNetworkInterfaces() []*NetworkInterface {
	if x != nil {
		return x.NetworkInterfaces
	}
	return nil
}

func (x *VMConfig) GetSerialPorts() []*SerialPortConfig {
	if x != nil {
		return x.SerialPorts
	}
	return nil
}

func (x *VMConfig) GetKernelImagePath() string {
	if x != nil {
		return x.KernelImagePath
	}
	return ""
}

func (x *VMConfig) GetInitrdPath() string {
	if x != nil {
		return x.InitrdPath
	}
	return ""
}

func (x *VMConfig) GetKernelCmdline() string {
	if x != nil {
		return x.KernelCmdline
	}
	return ""
}

func (x *VMConfig) GetArch() VirtualHardwareArch {
	if x != nil {
		return x.Arch
	}
	return VirtualHardwareArch_ARCH_UNSPECIFIED
}

func (x *VMConfig) GetVcpuConfig() *VCPUConfig {
	if x != nil {
		return x.VcpuConfig
	}
	return nil
}

func (x *VMConfig) GetMemoryConfig() *MemoryConfig {
	if x != nil {
		return x.MemoryConfig
	}
	return nil
}

func (x *VMConfig) GetAiHardwareConfig() *AIHardwareConfig {
	if x != nil {
		return x.AiHardwareConfig
	}
	return nil
}

func (x *VMConfig) GetGraphicsConfig() *GraphicsConfig {
	if x != nil {
		return x.GraphicsConfig
	}
	return nil
}

func (x *VMConfig) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *VMConfig) GetBootOrder() []string {
	if x != nil {
		return x.BootOrder
	}
	return nil
}

func (x *VMConfig) GetFirmwareType() VMConfig_FirmwareType {
	if x != nil {
		return x.FirmwareType
	}
	return VMConfig_FIRMWARE_TYPE_UNSPECIFIED
}

func (x *VMConfig) GetSecureBootEnabled() bool {
	if x != nil {
		return x.SecureBootEnabled
	}
	return false
}

func (x *VMConfig) GetVirtualTpmEnabled() bool {
	if x != nil {
		return x.VirtualTpmEnabled
	}
	return false
}

func (x *VMConfig) GetPciPassthroughDevices() []*PCIPassthroughDevice {
	if x != nil {
		return x.PciPassthroughDevices
	}
	return nil
}

type CreateVMRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Config         *VMConfig              `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	VmIdSuggestion string                 `protobuf:"bytes,2,opt,name=vm_id_suggestion,json=vmIdSuggestion,proto3" json:"vm_id_suggestion,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateVMRequest) Reset() {
	*x = CreateVMRequest{}
	mi := &file_v_architect_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVMRequest) ProtoMessage() {}

func (x *CreateVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVMRequest.ProtoReflect.Descriptor instead.
func (*CreateVMRequest) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{9}
}

func (x *CreateVMRequest) GetConfig() *VMConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CreateVMRequest) GetVmIdSuggestion() string {
	if x != nil {
		return x.VmIdSuggestion
	}
	return ""
}

type CreateVMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVMResponse) Reset() {
	*x = CreateVMResponse{}
	mi := &file_v_architect_core_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVMResponse) ProtoMessage() {}

func (x *CreateVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVMResponse.ProtoReflect.Descriptor instead.
func (*CreateVMResponse) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{10}
}

func (x *CreateVMResponse) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *CreateVMResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateVMResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StartVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"` // Boot parameters moved to VMConfig for persistence and clarity
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVMRequest) Reset() {
	*x = StartVMRequest{}
	mi := &file_v_architect_core_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVMRequest) ProtoMessage() {}

func (x *StartVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVMRequest.ProtoReflect.Descriptor instead.
func (*StartVMRequest) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{11}
}

func (x *StartVMRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type StartVMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVMResponse) Reset() {
	*x = StartVMResponse{}
	mi := &file_v_architect_core_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVMResponse) ProtoMessage() {}

func (x *StartVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVMResponse.ProtoReflect.Descriptor instead.
func (*StartVMResponse) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{12}
}

func (x *StartVMResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartVMResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StopVMRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VmId           string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Force          bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	TimeoutSeconds uint32                 `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StopVMRequest) Reset() {
	*x = StopVMRequest{}
	mi := &file_v_architect_core_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVMRequest) ProtoMessage() {}

func (x *StopVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopVMRequest.ProtoReflect.Descriptor instead.
func (*StopVMRequest) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{13}
}

func (x *StopVMRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *StopVMRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *StopVMRequest) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type StopVMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopVMResponse) Reset() {
	*x = StopVMResponse{}
	mi := &file_v_architect_core_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVMResponse) ProtoMessage() {}

func (x *StopVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopVMResponse.ProtoReflect.Descriptor instead.
func (*StopVMResponse) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{14}
}

func (x *StopVMResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopVMResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Adding other messages from finalized proto for completeness
type GetEngineInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEngineInfoRequest) Reset() {
	*x = GetEngineInfoRequest{}
	mi := &file_v_architect_core_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEngineInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEngineInfoRequest) ProtoMessage() {}

func (x *GetEngineInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEngineInfoRequest.ProtoReflect.Descriptor instead.
func (*GetEngineInfoRequest) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{15}
}

type GetEngineInfoResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	EngineVersion            string                 `protobuf:"bytes,1,opt,name=engine_version,json=engineVersion,proto3" json:"engine_version,omitempty"`
	ApiVersion               string                 `protobuf:"bytes,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	SupportedVmArchitectures []string               `protobuf:"bytes,3,rep,name=supported_vm_architectures,json=supportedVmArchitectures,proto3" json:"supported_vm_architectures,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *GetEngineInfoResponse) Reset() {
	*x = GetEngineInfoResponse{}
	mi := &file_v_architect_core_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEngineInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEngineInfoResponse) ProtoMessage() {}

func (x *GetEngineInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEngineInfoResponse.ProtoReflect.Descriptor instead.
func (*GetEngineInfoResponse) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{16}
}

func (x *GetEngineInfoResponse) GetEngineVersion() string {
	if x != nil {
		return x.EngineVersion
	}
	return ""
}

func (x *GetEngineInfoResponse) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *GetEngineInfoResponse) GetSupportedVmArchitectures() []string {
	if x != nil {
		return x.SupportedVmArchitectures
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_v_architect_core_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{17}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Status        HealthCheckResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=proto.HealthCheckResponse_Status" json:"status,omitempty"`
	Message       string                     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_v_architect_core_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{18}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_Status {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ConfigureEngineRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	LogLevel           string                 `protobuf:"bytes,1,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	DefaultStoragePath string                 `protobuf:"bytes,2,opt,name=default_storage_path,json=defaultStoragePath,proto3" json:"default_storage_path,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ConfigureEngineRequest) Reset() {
	*x = ConfigureEngineRequest{}
	mi := &file_v_architect_core_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureEngineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureEngineRequest) ProtoMessage() {}

func (x *ConfigureEngineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureEngineRequest.ProtoReflect.Descriptor instead.
func (*ConfigureEngineRequest) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{19}
}

func (x *ConfigureEngineRequest) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

func (x *ConfigureEngineRequest) GetDefaultStoragePath() string {
	if x != nil {
		return x.DefaultStoragePath
	}
	return ""
}

type ConfigureEngineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureEngineResponse) Reset() {
	*x = ConfigureEngineResponse{}
	mi := &file_v_architect_core_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureEngineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureEngineResponse) ProtoMessage() {}

func (x *ConfigureEngineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureEngineResponse.ProtoReflect.Descriptor instead.
func (*ConfigureEngineResponse) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{20}
}

func (x *ConfigureEngineResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigureEngineResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetHostCapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHostCapabilitiesRequest) Reset() {
	*x = GetHostCapabilitiesRequest{}
	mi := &file_v_architect_core_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostCapabilitiesRequest) ProtoMessage() {}

func (x *GetHostCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*GetHostCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{21}
}

type HostCapabilities struct {
	state                  protoimpl.MessageState                `protogen:"open.v1"`
	CpuInfo                *HostCapabilities_CPUInfo             `protobuf:"bytes,1,opt,name=cpu_info,json=cpuInfo,proto3" json:"cpu_info,omitempty"`
	TotalMemoryGb          uint64                                `protobuf:"varint,2,opt,name=total_memory_gb,json=totalMemoryGb,proto3" json:"total_memory_gb,omitempty"`
	AvailableMemoryGb      uint64                                `protobuf:"varint,3,opt,name=available_memory_gb,json=availableMemoryGb,proto3" json:"available_memory_gb,omitempty"`
	StoragePools           []*HostCapabilities_StoragePoolInfo   `protobuf:"bytes,4,rep,name=storage_pools,json=storagePools,proto3" json:"storage_pools,omitempty"`
	DetectedGpus           []*HostCapabilities_GPUInfo           `protobuf:"bytes,5,rep,name=detected_gpus,json=detectedGpus,proto3" json:"detected_gpus,omitempty"`
	DetectedAiAccelerators []*HostCapabilities_AIAcceleratorInfo `protobuf:"bytes,6,rep,name=detected_ai_accelerators,json=detectedAiAccelerators,proto3" json:"detected_ai_accelerators,omitempty"`
	KvmCapabilitiesPresent []string                              `protobuf:"bytes,7,rep,name=kvm_capabilities_present,json=kvmCapabilitiesPresent,proto3" json:"kvm_capabilities_present,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *HostCapabilities) Reset() {
	*x = HostCapabilities{}
	mi := &file_v_architect_core_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostCapabilities) ProtoMessage() {}

func (x *HostCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostCapabilities.ProtoReflect.Descriptor instead.
func (*HostCapabilities) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{22}
}

func (x *HostCapabilities) GetCpuInfo() *HostCapabilities_CPUInfo {
	if x != nil {
		return x.CpuInfo
	}
	return nil
}

func (x *HostCapabilities) GetTotalMemoryGb() uint64 {
	if x != nil {
		return x.TotalMemoryGb
	}
	return 0
}

func (x *HostCapabilities) GetAvailableMemoryGb() uint64 {
	if x != nil {
		return x.AvailableMemoryGb
	}
	return 0
}

func (x *HostCapabilities) GetStoragePools() []*HostCapabilities_StoragePoolInfo {
	if x != nil {
		return x.StoragePools
	}
	return nil
}

func (x *HostCapabilities) GetDetectedGpus() []*HostCapabilities_GPUInfo {
	if x != nil {
		return x.DetectedGpus
	}
	return nil
}

func (x *HostCapabilities) GetDetectedAiAccelerators() []*HostCapabilities_AIAcceleratorInfo {
	if x != nil {
		return x.DetectedAiAccelerators
	}
	return nil
}

func (x *HostCapabilities) GetKvmCapabilitiesPresent() []string {
	if x != nil {
		return x.KvmCapabilitiesPresent
	}
	return nil
}

type VCPUConfig_Topology struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Sockets        uint32                 `protobuf:"varint,1,opt,name=sockets,proto3" json:"sockets,omitempty"`
	CoresPerSocket uint32                 `protobuf:"varint,2,opt,name=cores_per_socket,json=coresPerSocket,proto3" json:"cores_per_socket,omitempty"`
	ThreadsPerCore uint32                 `protobuf:"varint,3,opt,name=threads_per_core,json=threadsPerCore,proto3" json:"threads_per_core,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VCPUConfig_Topology) Reset() {
	*x = VCPUConfig_Topology{}
	mi := &file_v_architect_core_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VCPUConfig_Topology) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VCPUConfig_Topology) ProtoMessage() {}

func (x *VCPUConfig_Topology) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VCPUConfig_Topology.ProtoReflect.Descriptor instead.
func (*VCPUConfig_Topology) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{3, 0}
}

func (x *VCPUConfig_Topology) GetSockets() uint32 {
	if x != nil {
		return x.Sockets
	}
	return 0
}

func (x *VCPUConfig_Topology) GetCoresPerSocket() uint32 {
	if x != nil {
		return x.CoresPerSocket
	}
	return 0
}

func (x *VCPUConfig_Topology) GetThreadsPerCore() uint32 {
	if x != nil {
		return x.ThreadsPerCore
	}
	return 0
}

type MemoryConfig_AIOptimizedFlags struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	PreferContiguousHostMemory bool                   `protobuf:"varint,1,opt,name=prefer_contiguous_host_memory,json=preferContiguousHostMemory,proto3" json:"prefer_contiguous_host_memory,omitempty"`
	NumaNodeAffinity           uint32                 `protobuf:"varint,2,opt,name=numa_node_affinity,json=numaNodeAffinity,proto3" json:"numa_node_affinity,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *MemoryConfig_AIOptimizedFlags) Reset() {
	*x = MemoryConfig_AIOptimizedFlags{}
	mi := &file_v_architect_core_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryConfig_AIOptimizedFlags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryConfig_AIOptimizedFlags) ProtoMessage() {}

func (x *MemoryConfig_AIOptimizedFlags) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryConfig_AIOptimizedFlags.ProtoReflect.Descriptor instead.
func (*MemoryConfig_AIOptimizedFlags) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{4, 0}
}

func (x *MemoryConfig_AIOptimizedFlags) GetPreferContiguousHostMemory() bool {
	if x != nil {
		return x.PreferContiguousHostMemory
	}
	return false
}

func (x *MemoryConfig_AIOptimizedFlags) GetNumaNodeAffinity() uint32 {
	if x != nil {
		return x.NumaNodeAffinity
	}
	return 0
}

type HostCapabilities_CPUInfo struct {
	state                             protoimpl.MessageState `protogen:"open.v1"`
	ModelString                       string                 `protobuf:"bytes,1,opt,name=model_string,json=modelString,proto3" json:"model_string,omitempty"`
	CoreCount                         uint32                 `protobuf:"varint,2,opt,name=core_count,json=coreCount,proto3" json:"core_count,omitempty"`
	ThreadCount                       uint32                 `protobuf:"varint,3,opt,name=thread_count,json=threadCount,proto3" json:"thread_count,omitempty"`
	SupportedVirtualizationExtensions []string               `protobuf:"bytes,4,rep,name=supported_virtualization_extensions,json=supportedVirtualizationExtensions,proto3" json:"supported_virtualization_extensions,omitempty"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *HostCapabilities_CPUInfo) Reset() {
	*x = HostCapabilities_CPUInfo{}
	mi := &file_v_architect_core_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostCapabilities_CPUInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostCapabilities_CPUInfo) ProtoMessage() {}

func (x *HostCapabilities_CPUInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostCapabilities_CPUInfo.ProtoReflect.Descriptor instead.
func (*HostCapabilities_CPUInfo) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{22, 0}
}

func (x *HostCapabilities_CPUInfo) GetModelString() string {
	if x != nil {
		return x.ModelString
	}
	return ""
}

func (x *HostCapabilities_CPUInfo) GetCoreCount() uint32 {
	if x != nil {
		return x.CoreCount
	}
	return 0
}

func (x *HostCapabilities_CPUInfo) GetThreadCount() uint32 {
	if x != nil {
		return x.ThreadCount
	}
	return 0
}

func (x *HostCapabilities_CPUInfo) GetSupportedVirtualizationExtensions() []string {
	if x != nil {
		return x.SupportedVirtualizationExtensions
	}
	return nil
}

type HostCapabilities_StoragePoolInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PoolId           string                 `protobuf:"bytes,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	Path             string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	TotalSpaceGb     uint64                 `protobuf:"varint,3,opt,name=total_space_gb,json=totalSpaceGb,proto3" json:"total_space_gb,omitempty"`
	AvailableSpaceGb uint64                 `protobuf:"varint,4,opt,name=available_space_gb,json=availableSpaceGb,proto3" json:"available_space_gb,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HostCapabilities_StoragePoolInfo) Reset() {
	*x = HostCapabilities_StoragePoolInfo{}
	mi := &file_v_architect_core_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostCapabilities_StoragePoolInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostCapabilities_StoragePoolInfo) ProtoMessage() {}

func (x *HostCapabilities_StoragePoolInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostCapabilities_StoragePoolInfo.ProtoReflect.Descriptor instead.
func (*HostCapabilities_StoragePoolInfo) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{22, 1}
}

func (x *HostCapabilities_StoragePoolInfo) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

func (x *HostCapabilities_StoragePoolInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HostCapabilities_StoragePoolInfo) GetTotalSpaceGb() uint64 {
	if x != nil {
		return x.TotalSpaceGb
	}
	return 0
}

func (x *HostCapabilities_StoragePoolInfo) GetAvailableSpaceGb() uint64 {
	if x != nil {
		return x.AvailableSpaceGb
	}
	return 0
}

type HostCapabilities_GPUInfo struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	GpuId                   string                 `protobuf:"bytes,1,opt,name=gpu_id,json=gpuId,proto3" json:"gpu_id,omitempty"`
	VendorId                string                 `protobuf:"bytes,2,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	DeviceId                string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ModelName               string                 `protobuf:"bytes,4,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	MemoryMb                uint64                 `protobuf:"varint,5,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	PassthroughCapable      bool                   `protobuf:"varint,6,opt,name=passthrough_capable,json=passthroughCapable,proto3" json:"passthrough_capable,omitempty"`
	AvailableForPassthrough bool                   `protobuf:"varint,7,opt,name=available_for_passthrough,json=availableForPassthrough,proto3" json:"available_for_passthrough,omitempty"`
	VgpuProfilesSupported   []string               `protobuf:"bytes,8,rep,name=vgpu_profiles_supported,json=vgpuProfilesSupported,proto3" json:"vgpu_profiles_supported,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *HostCapabilities_GPUInfo) Reset() {
	*x = HostCapabilities_GPUInfo{}
	mi := &file_v_architect_core_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostCapabilities_GPUInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostCapabilities_GPUInfo) ProtoMessage() {}

func (x *HostCapabilities_GPUInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostCapabilities_GPUInfo.ProtoReflect.Descriptor instead.
func (*HostCapabilities_GPUInfo) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{22, 2}
}

func (x *HostCapabilities_GPUInfo) GetGpuId() string {
	if x != nil {
		return x.GpuId
	}
	return ""
}

func (x *HostCapabilities_GPUInfo) GetVendorId() string {
	if x != nil {
		return x.VendorId
	}
	return ""
}

func (x *HostCapabilities_GPUInfo) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *HostCapabilities_GPUInfo) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *HostCapabilities_GPUInfo) GetMemoryMb() uint64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *HostCapabilities_GPUInfo) GetPassthroughCapable() bool {
	if x != nil {
		return x.PassthroughCapable
	}
	return false
}

func (x *HostCapabilities_GPUInfo) GetAvailableForPassthrough() bool {
	if x != nil {
		return x.AvailableForPassthrough
	}
	return false
}

func (x *HostCapabilities_GPUInfo) GetVgpuProfilesSupported() []string {
	if x != nil {
		return x.VgpuProfilesSupported
	}
	return nil
}

type HostCapabilities_AIAcceleratorInfo struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	AcceleratorId             string                 `protobuf:"bytes,1,opt,name=accelerator_id,json=acceleratorId,proto3" json:"accelerator_id,omitempty"`
	VendorId                  string                 `protobuf:"bytes,2,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	DeviceId                  string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Type                      string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	ModelName                 string                 `protobuf:"bytes,5,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	PassthroughCapable        bool                   `protobuf:"varint,6,opt,name=passthrough_capable,json=passthroughCapable,proto3" json:"passthrough_capable,omitempty"`
	AvailableForPassthrough   bool                   `protobuf:"varint,7,opt,name=available_for_passthrough,json=availableForPassthrough,proto3" json:"available_for_passthrough,omitempty"`
	MediatedProfilesSupported []string               `protobuf:"bytes,8,rep,name=mediated_profiles_supported,json=mediatedProfilesSupported,proto3" json:"mediated_profiles_supported,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *HostCapabilities_AIAcceleratorInfo) Reset() {
	*x = HostCapabilities_AIAcceleratorInfo{}
	mi := &file_v_architect_core_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostCapabilities_AIAcceleratorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostCapabilities_AIAcceleratorInfo) ProtoMessage() {}

func (x *HostCapabilities_AIAcceleratorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostCapabilities_AIAcceleratorInfo.ProtoReflect.Descriptor instead.
func (*HostCapabilities_AIAcceleratorInfo) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{22, 3}
}

func (x *HostCapabilities_AIAcceleratorInfo) GetAcceleratorId() string {
	if x != nil {
		return x.AcceleratorId
	}
	return ""
}

func (x *HostCapabilities_AIAcceleratorInfo) GetVendorId() string {
	if x != nil {
		return x.VendorId
	}
	return ""
}

func (x *HostCapabilities_AIAcceleratorInfo) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *HostCapabilities_AIAcceleratorInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *HostCapabilities_AIAcceleratorInfo) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *HostCapabilities_AIAcceleratorInfo) GetPassthroughCapable() bool {
	if x != nil {
		return x.PassthroughCapable
	}
	return false
}

func (x *HostCapabilities_AIAcceleratorInfo) GetAvailableForPassthrough() bool {
	if x != nil {
		return x.AvailableForPassthrough
	}
	return false
}

func (x *HostCapabilities_AIAcceleratorInfo) GetMediatedProfilesSupported() []string {
	if x != nil {
		return x.MediatedProfilesSupported
	}
	return nil
}

var File_v_architect_core_proto protoreflect.FileDescriptor

const file_v_architect_core_proto_rawDesc = "" +
	"\n" +
	"\x16v_architect_core.proto\x12\x05proto\"T\n" +
	"\tDiskImage\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x1b\n" +
	"\tread_only\x18\x03 \x01(\bR\breadOnly\"\x7f\n" +
	"\x10NetworkInterface\x12\x15\n" +
	"\x06nic_id\x18\x01 \x01(\tR\x05nicId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1f\n" +
	"\vmac_address\x18\x03 \x01(\tR\n" +
	"macAddress\x12\x1f\n" +
	"\vbridge_name\x18\x04 \x01(\tR\n" +
	"bridgeName\"\xd4\x02\n" +
	"\x10SerialPortConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12:\n" +
	"\x04type\x18\x02 \x01(\x0e2&.proto.SerialPortConfig.SerialPortTypeR\x04type\x12&\n" +
	"\x0fpath_or_address\x18\x03 \x01(\tR\rpathOrAddress\x12(\n" +
	"\x10io_base_override\x18\x04 \x01(\rR\x0eioBaseOverride\"\xa1\x01\n" +
	"\x0eSerialPortType\x12\x1b\n" +
	"\x17SERIAL_TYPE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bLOG_ONLY\x10\x01\x12\t\n" +
	"\x05STDIO\x10\x02\x12\b\n" +
	"\x04FILE\x10\x03\x12\a\n" +
	"\x03PTY\x10\x04\x12\x15\n" +
	"\x11TCP_SOCKET_SERVER\x10\x05\x12\x15\n" +
	"\x11TCP_SOCKET_CLIENT\x10\x06\x12\x0e\n" +
	"\n" +
	"NAMED_PIPE\x10\a\x12\b\n" +
	"\x04NONE\x10\b\"\xad\x02\n" +
	"\n" +
	"VCPUConfig\x12\"\n" +
	"\renable_kvm_hv\x18\x01 \x01(\bR\venableKvmHv\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\x126\n" +
	"\btopology\x18\x03 \x01(\v2\x1a.proto.VCPUConfig.TopologyR\btopology\x123\n" +
	"\x16cpu_features_to_enable\x18\x04 \x03(\tR\x13cpuFeaturesToEnable\x1ax\n" +
	"\bTopology\x12\x18\n" +
	"\asockets\x18\x01 \x01(\rR\asockets\x12(\n" +
	"\x10cores_per_socket\x18\x02 \x01(\rR\x0ecoresPerSocket\x12(\n" +
	"\x10threads_per_core\x18\x03 \x01(\rR\x0ethreadsPerCore\"\xe1\x02\n" +
	"\fMemoryConfig\x12\x17\n" +
	"\asize_mb\x18\x01 \x01(\x04R\x06sizeMb\x12*\n" +
	"\x11enable_huge_pages\x18\x02 \x01(\bR\x0fenableHugePages\x122\n" +
	"\x15enable_mem_ballooning\x18\x03 \x01(\bR\x13enableMemBallooning\x12R\n" +
	"\x12ai_optimized_flags\x18\x04 \x01(\v2$.proto.MemoryConfig.AIOptimizedFlagsR\x10aiOptimizedFlags\x1a\x83\x01\n" +
	"\x10AIOptimizedFlags\x12A\n" +
	"\x1dprefer_contiguous_host_memory\x18\x01 \x01(\bR\x1apreferContiguousHostMemory\x12,\n" +
	"\x12numa_node_affinity\x18\x02 \x01(\rR\x10numaNodeAffinity\"Z\n" +
	"\x10AIHardwareConfig\x12\"\n" +
	"\renable_ai_cpu\x18\x01 \x01(\bR\venableAiCpu\x12\"\n" +
	"\renable_ai_gpu\x18\x02 \x01(\bR\venableAiGpu\"\x8c\x02\n" +
	"\x0eGraphicsConfig\x126\n" +
	"\x04type\x18\x01 \x01(\x0e2\".proto.GraphicsConfig.GraphicsTypeR\x04type\x12<\n" +
	"\x1bvgpu_profile_or_physical_id\x18\x02 \x01(\tR\x17vgpuProfileOrPhysicalId\"\x83\x01\n" +
	"\fGraphicsType\x12\x1d\n" +
	"\x19GRAPHICS_TYPE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04NONE\x10\x01\x12\x12\n" +
	"\x0eVGA_COMPATIBLE\x10\x02\x12\x0e\n" +
	"\n" +
	"VIRTIO_GPU\x10\x03\x12\x13\n" +
	"\x0fGPU_PASSTHROUGH\x10\x04\x12\x11\n" +
	"\rMEDIATED_VGPU\x10\x05\"j\n" +
	"\x14PCIPassthroughDevice\x12(\n" +
	"\x10host_pci_address\x18\x01 \x01(\tR\x0ehostPciAddress\x12(\n" +
	"\x10iommu_group_path\x18\x02 \x01(\tR\x0eiommuGroupPath\"\xd5\b\n" +
	"\bVMConfig\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x121\n" +
	"\vdisk_images\x18\x05 \x03(\v2\x10.proto.DiskImageR\n" +
	"diskImages\x12F\n" +
	"\x12network_interfaces\x18\x06 \x03(\v2\x17.proto.NetworkInterfaceR\x11networkInterfaces\x12:\n" +
	"\fserial_ports\x18\a \x03(\v2\x17.proto.SerialPortConfigR\vserialPorts\x12*\n" +
	"\x11kernel_image_path\x18\t \x01(\tR\x0fkernelImagePath\x12\x1f\n" +
	"\vinitrd_path\x18\n" +
	" \x01(\tR\n" +
	"initrdPath\x12%\n" +
	"\x0ekernel_cmdline\x18\v \x01(\tR\rkernelCmdline\x12.\n" +
	"\x04arch\x18\f \x01(\x0e2\x1a.proto.VirtualHardwareArchR\x04arch\x122\n" +
	"\vvcpu_config\x18\r \x01(\v2\x11.proto.VCPUConfigR\n" +
	"vcpuConfig\x128\n" +
	"\rmemory_config\x18\x0e \x01(\v2\x13.proto.MemoryConfigR\fmemoryConfig\x12E\n" +
	"\x12ai_hardware_config\x18\x0f \x01(\v2\x17.proto.AIHardwareConfigR\x10aiHardwareConfig\x12>\n" +
	"\x0fgraphics_config\x18\x13 \x01(\v2\x15.proto.GraphicsConfigR\x0egraphicsConfig\x129\n" +
	"\bmetadata\x18\x10 \x03(\v2\x1d.proto.VMConfig.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"boot_order\x18\x14 \x03(\tR\tbootOrder\x12A\n" +
	"\rfirmware_type\x18\x15 \x01(\x0e2\x1c.proto.VMConfig.FirmwareTypeR\ffirmwareType\x12.\n" +
	"\x13secure_boot_enabled\x18\x16 \x01(\bR\x11secureBootEnabled\x12.\n" +
	"\x13virtual_tpm_enabled\x18\x17 \x01(\bR\x11virtualTpmEnabled\x12S\n" +
	"\x17pci_passthrough_devices\x18\x18 \x03(\v2\x1b.proto.PCIPassthroughDeviceR\x15pciPassthroughDevices\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"A\n" +
	"\fFirmwareType\x12\x1d\n" +
	"\x19FIRMWARE_TYPE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04BIOS\x10\x01\x12\b\n" +
	"\x04UEFI\x10\x02\"d\n" +
	"\x0fCreateVMRequest\x12'\n" +
	"\x06config\x18\x01 \x01(\v2\x0f.proto.VMConfigR\x06config\x12(\n" +
	"\x10vm_id_suggestion\x18\x02 \x01(\tR\x0evmIdSuggestion\"[\n" +
	"\x10CreateVMResponse\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"%\n" +
	"\x0eStartVMRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"E\n" +
	"\x0fStartVMResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"c\n" +
	"\rStopVMRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\rR\x0etimeoutSeconds\"D\n" +
	"\x0eStopVMResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x16\n" +
	"\x14GetEngineInfoRequest\"\x9d\x01\n" +
	"\x15GetEngineInfoResponse\x12%\n" +
	"\x0eengine_version\x18\x01 \x01(\tR\rengineVersion\x12\x1f\n" +
	"\vapi_version\x18\x02 \x01(\tR\n" +
	"apiVersion\x12<\n" +
	"\x1asupported_vm_architectures\x18\x03 \x03(\tR\x18supportedVmArchitectures\"\x14\n" +
	"\x12HealthCheckRequest\"\xab\x01\n" +
	"\x13HealthCheckResponse\x129\n" +
	"\x06status\x18\x01 \x01(\x0e2!.proto.HealthCheckResponse.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"?\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aHEALTHY\x10\x01\x12\f\n" +
	"\bDEGRADED\x10\x02\x12\r\n" +
	"\tUNHEALTHY\x10\x03\"g\n" +
	"\x16ConfigureEngineRequest\x12\x1b\n" +
	"\tlog_level\x18\x01 \x01(\tR\blogLevel\x120\n" +
	"\x14default_storage_path\x18\x02 \x01(\tR\x12defaultStoragePath\"M\n" +
	"\x17ConfigureEngineResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x1c\n" +
	"\x1aGetHostCapabilitiesRequest\"\xc4\v\n" +
	"\x10HostCapabilities\x12:\n" +
	"\bcpu_info\x18\x01 \x01(\v2\x1f.proto.HostCapabilities.CPUInfoR\acpuInfo\x12&\n" +
	"\x0ftotal_memory_gb\x18\x02 \x01(\x04R\rtotalMemoryGb\x12.\n" +
	"\x13available_memory_gb\x18\x03 \x01(\x04R\x11availableMemoryGb\x12L\n" +
	"\rstorage_pools\x18\x04 \x03(\v2'.proto.HostCapabilities.StoragePoolInfoR\fstoragePools\x12D\n" +
	"\rdetected_gpus\x18\x05 \x03(\v2\x1f.proto.HostCapabilities.GPUInfoR\fdetectedGpus\x12c\n" +
	"\x18detected_ai_accelerators\x18\x06 \x03(\v2).proto.HostCapabilities.AIAcceleratorInfoR\x16detectedAiAccelerators\x128\n" +
	"\x18kvm_capabilities_present\x18\a \x03(\tR\x16kvmCapabilitiesPresent\x1a\xbe\x01\n" +
	"\aCPUInfo\x12!\n" +
	"\fmodel_string\x18\x01 \x01(\tR\vmodelString\x12\x1d\n" +
	"\n" +
	"core_count\x18\x02 \x01(\rR\tcoreCount\x12!\n" +
	"\fthread_count\x18\x03 \x01(\rR\vthreadCount\x12N\n" +
	"#supported_virtualization_extensions\x18\x04 \x03(\tR!supportedVirtualizationExtensions\x1a\x92\x01\n" +
	"\x0fStoragePoolInfo\x12\x17\n" +
	"\apool_id\x18\x01 \x01(\tR\x06poolId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12$\n" +
	"\x0etotal_space_gb\x18\x03 \x01(\x04R\ftotalSpaceGb\x12,\n" +
	"\x12available_space_gb\x18\x04 \x01(\x04R\x10availableSpaceGb\x1a\xbb\x02\n" +
	"\aGPUInfo\x12\x15\n" +
	"\x06gpu_id\x18\x01 \x01(\tR\x05gpuId\x12\x1b\n" +
	"\tvendor_id\x18\x02 \x01(\tR\bvendorId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"model_name\x18\x04 \x01(\tR\tmodelName\x12\x1b\n" +
	"\tmemory_mb\x18\x05 \x01(\x04R\bmemoryMb\x12/\n" +
	"\x13passthrough_capable\x18\x06 \x01(\bR\x12passthroughCapable\x12:\n" +
	"\x19available_for_passthrough\x18\a \x01(\bR\x17availableForPassthrough\x126\n" +
	"\x17vgpu_profiles_supported\x18\b \x03(\tR\x15vgpuProfilesSupported\x1a\xd4\x02\n" +
	"\x11AIAcceleratorInfo\x12%\n" +
	"\x0eaccelerator_id\x18\x01 \x01(\tR\racceleratorId\x12\x1b\n" +
	"\tvendor_id\x18\x02 \x01(\tR\bvendorId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"model_name\x18\x05 \x01(\tR\tmodelName\x12/\n" +
	"\x13passthrough_capable\x18\x06 \x01(\bR\x12passthroughCapable\x12:\n" +
	"\x19available_for_passthrough\x18\a \x01(\bR\x17availableForPassthrough\x12>\n" +
	"\x1bmediated_profiles_supported\x18\b \x03(\tR\x19mediatedProfilesSupported*B\n" +
	"\x13VirtualHardwareArch\x12\x14\n" +
	"\x10ARCH_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06X86_64\x10\x01\x12\t\n" +
	"\x05ARM64\x10\x022\x8b\x03\n" +
	"\x15CoreHypervisorService\x12;\n" +
	"\bCreateVM\x12\x16.proto.CreateVMRequest\x1a\x17.proto.CreateVMResponse\x12J\n" +
	"\rGetEngineInfo\x12\x1b.proto.GetEngineInfoRequest\x1a\x1c.proto.GetEngineInfoResponse\x12D\n" +
	"\vHealthCheck\x12\x19.proto.HealthCheckRequest\x1a\x1a.proto.HealthCheckResponse\x12P\n" +
	"\x0fConfigureEngine\x12\x1d.proto.ConfigureEngineRequest\x1a\x1e.proto.ConfigureEngineResponse\x12Q\n" +
	"\x13GetHostCapabilities\x12!.proto.GetHostCapabilitiesRequest\x1a\x17.proto.HostCapabilities2|\n" +
	"\tVMService\x128\n" +
	"\aStartVM\x12\x15.proto.StartVMRequest\x1a\x16.proto.StartVMResponse\x125\n" +
	"\x06StopVM\x12\x14.proto.StopVMRequest\x1a\x15.proto.StopVMResponseB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_v_architect_core_proto_rawDescOnce sync.Once
	file_v_architect_core_proto_rawDescData []byte
)

func file_v_architect_core_proto_rawDescGZIP() []byte {
	file_v_architect_core_proto_rawDescOnce.Do(func() {
		file_v_architect_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v_architect_core_proto_rawDesc), len(file_v_architect_core_proto_rawDesc)))
	})
	return file_v_architect_core_proto_rawDescData
}

var file_v_architect_core_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_v_architect_core_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_v_architect_core_proto_goTypes = []any{
	(VirtualHardwareArch)(0),                   // 0: proto.VirtualHardwareArch
	(SerialPortConfig_SerialPortType)(0),       // 1: proto.SerialPortConfig.SerialPortType
	(GraphicsConfig_GraphicsType)(0),           // 2: proto.GraphicsConfig.GraphicsType
	(VMConfig_FirmwareType)(0),                 // 3: proto.VMConfig.FirmwareType
	(HealthCheckResponse_Status)(0),            // 4: proto.HealthCheckResponse.Status
	(*DiskImage)(nil),                          // 5: proto.DiskImage
	(*NetworkInterface)(nil),                   // 6: proto.NetworkInterface
	(*SerialPortConfig)(nil),                   // 7: proto.SerialPortConfig
	(*VCPUConfig)(nil),                         // 8: proto.VCPUConfig
	(*MemoryConfig)(nil),                       // 9: proto.MemoryConfig
	(*AIHardwareConfig)(nil),                   // 10: proto.AIHardwareConfig
	(*GraphicsConfig)(nil),                     // 11: proto.GraphicsConfig
	(*PCIPassthroughDevice)(nil),               // 12: proto.PCIPassthroughDevice
	(*VMConfig)(nil),                           // 13: proto.VMConfig
	(*CreateVMRequest)(nil),                    // 14: proto.CreateVMRequest
	(*CreateVMResponse)(nil),                   // 15: proto.CreateVMResponse
	(*StartVMRequest)(nil),                     // 16: proto.StartVMRequest
	(*StartVMResponse)(nil),                    // 17: proto.StartVMResponse
	(*StopVMRequest)(nil),                      // 18: proto.StopVMRequest
	(*StopVMResponse)(nil),                     // 19: proto.StopVMResponse
	(*GetEngineInfoRequest)(nil),               // 20: proto.GetEngineInfoRequest
	(*GetEngineInfoResponse)(nil),              // 21: proto.GetEngineInfoResponse
	(*HealthCheckRequest)(nil),                 // 22: proto.HealthCheckRequest
	(*HealthCheckResponse)(nil),                // 23: proto.HealthCheckResponse
	(*ConfigureEngineRequest)(nil),             // 24: proto.ConfigureEngineRequest
	(*ConfigureEngineResponse)(nil),            // 25: proto.ConfigureEngineResponse
	(*GetHostCapabilitiesRequest)(nil),         // 26: proto.GetHostCapabilitiesRequest
	(*HostCapabilities)(nil),                   // 27: proto.HostCapabilities
	(*VCPUConfig_Topology)(nil),                // 28: proto.VCPUConfig.Topology
	(*MemoryConfig_AIOptimizedFlags)(nil),      // 29: proto.MemoryConfig.AIOptimizedFlags
	nil,                                        // 30: proto.VMConfig.MetadataEntry
	(*HostCapabilities_CPUInfo)(nil),           // 31: proto.HostCapabilities.CPUInfo
	(*HostCapabilities_StoragePoolInfo)(nil),   // 32: proto.HostCapabilities.StoragePoolInfo
	(*HostCapabilities_GPUInfo)(nil),           // 33: proto.HostCapabilities.GPUInfo
	(*HostCapabilities_AIAcceleratorInfo)(nil), // 34: proto.HostCapabilities.AIAcceleratorInfo
}
var file_v_architect_core_proto_depIdxs = []int32{
	1,  // 0: proto.SerialPortConfig.type:type_name -> proto.SerialPortConfig.SerialPortType
	28, // 1: proto.VCPUConfig.topology:type_name -> proto.VCPUConfig.Topology
	29, // 2: proto.MemoryConfig.ai_optimized_flags:type_name -> proto.MemoryConfig.AIOptimizedFlags
	2,  // 3: proto.GraphicsConfig.type:type_name -> proto.GraphicsConfig.GraphicsType
	5,  // 4: proto.VMConfig.disk_images:type_name -> proto.DiskImage
	6,  // 5: proto.VMConfig.network_interfaces:type_name -> proto.NetworkInterface
	7,  // 6: proto.VMConfig.serial_ports:type_name -> proto.SerialPortConfig
	0,  // 7: proto.VMConfig.arch:type_name -> proto.VirtualHardwareArch
	8,  // 8: proto.VMConfig.vcpu_config:type_name -> proto.VCPUConfig
	9,  // 9: proto.VMConfig.memory_config:type_name -> proto.MemoryConfig
	10, // 10: proto.VMConfig.ai_hardware_config:type_name -> proto.AIHardwareConfig
	11, // 11: proto.VMConfig.graphics_config:type_name -> proto.GraphicsConfig
	30, // 12: proto.VMConfig.metadata:type_name -> proto.VMConfig.MetadataEntry
	3,  // 13: proto.VMConfig.firmware_type:type_name -> proto.VMConfig.FirmwareType
	12, // 14: proto.VMConfig.pci_passthrough_devices:type_name -> proto.PCIPassthroughDevice
	13, // 15: proto.CreateVMRequest.config:type_name -> proto.VMConfig
	4,  // 16: proto.HealthCheckResponse.status:type_name -> proto.HealthCheckResponse.Status
	31, // 17: proto.HostCapabilities.cpu_info:type_name -> proto.HostCapabilities.CPUInfo
	32, // 18: proto.HostCapabilities.storage_pools:type_name -> proto.HostCapabilities.StoragePoolInfo
	33, // 19: proto.HostCapabilities.detected_gpus:type_name -> proto.HostCapabilities.GPUInfo
	34, // 20: proto.HostCapabilities.detected_ai_accelerators:type_name -> proto.HostCapabilities.AIAcceleratorInfo
	14, // 21: proto.CoreHypervisorService.CreateVM:input_type -> proto.CreateVMRequest
	20, // 22: proto.CoreHypervisorService.GetEngineInfo:input_type -> proto.GetEngineInfoRequest
	22, // 23: proto.CoreHypervisorService.HealthCheck:input_type -> proto.HealthCheckRequest
	24, // 24: proto.CoreHypervisorService.ConfigureEngine:input_type -> proto.ConfigureEngineRequest
	26, // 25: proto.CoreHypervisorService.GetHostCapabilities:input_type -> proto.GetHostCapabilitiesRequest
	16, // 26: proto.VMService.StartVM:input_type -> proto.StartVMRequest
	18, // 27: proto.VMService.StopVM:input_type -> proto.StopVMRequest
	15, // 28: proto.CoreHypervisorService.CreateVM:output_type -> proto.CreateVMResponse
	21, // 29: proto.CoreHypervisorService.GetEngineInfo:output_type -> proto.GetEngineInfoResponse
	23, // 30: proto.CoreHypervisorService.HealthCheck:output_type -> proto.HealthCheckResponse
	25, // 31: proto.CoreHypervisorService.ConfigureEngine:output_type -> proto.ConfigureEngineResponse
	27, // 32: proto.CoreHypervisorService.GetHostCapabilities:output_type -> proto.HostCapabilities
	17, // 33: proto.VMService.StartVM:output_type -> proto.StartVMResponse
	19, // 34: proto.VMService.StopVM:output_type -> proto.StopVMResponse
	28, // [28:35] is the sub-list for method output_type
	21, // [21:28] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_v_architect_core_proto_init() }
func file_v_architect_core_proto_init() {
	if File_v_architect_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v_architect_core_proto_rawDesc), len(file_v_architect_core_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_v_architect_core_proto_goTypes,
		DependencyIndexes: file_v_architect_core_proto_depIdxs,
		EnumInfos:         file_v_architect_core_proto_enumTypes,
		MessageInfos:      file_v_architect_core_proto_msgTypes,
	}.Build()
	File_v_architect_core_proto = out.File
	file_v_architect_core_proto_goTypes = nil
	file_v_architect_core_proto_depIdxs = nil
}
