// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: vm.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoreHypervisorService_GetHypervisorInfo_FullMethodName = "/proto.CoreHypervisorService/GetHypervisorInfo"
)

// CoreHypervisorServiceClient is the client API for CoreHypervisorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CoreHypervisorService provides information about the hypervisor.
type CoreHypervisorServiceClient interface {
	// GetHypervisorInfo returns basic information about the hypervisor.
	GetHypervisorInfo(ctx context.Context, in *GetHypervisorInfoRequest, opts ...grpc.CallOption) (*GetHypervisorInfoResponse, error)
}

type coreHypervisorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreHypervisorServiceClient(cc grpc.ClientConnInterface) CoreHypervisorServiceClient {
	return &coreHypervisorServiceClient{cc}
}

func (c *coreHypervisorServiceClient) GetHypervisorInfo(ctx context.Context, in *GetHypervisorInfoRequest, opts ...grpc.CallOption) (*GetHypervisorInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHypervisorInfoResponse)
	err := c.cc.Invoke(ctx, CoreHypervisorService_GetHypervisorInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreHypervisorServiceServer is the server API for CoreHypervisorService service.
// All implementations must embed UnimplementedCoreHypervisorServiceServer
// for forward compatibility.
//
// CoreHypervisorService provides information about the hypervisor.
type CoreHypervisorServiceServer interface {
	// GetHypervisorInfo returns basic information about the hypervisor.
	GetHypervisorInfo(context.Context, *GetHypervisorInfoRequest) (*GetHypervisorInfoResponse, error)
	mustEmbedUnimplementedCoreHypervisorServiceServer()
}

// UnimplementedCoreHypervisorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreHypervisorServiceServer struct{}

func (UnimplementedCoreHypervisorServiceServer) GetHypervisorInfo(context.Context, *GetHypervisorInfoRequest) (*GetHypervisorInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHypervisorInfo not implemented")
}
func (UnimplementedCoreHypervisorServiceServer) mustEmbedUnimplementedCoreHypervisorServiceServer() {}
func (UnimplementedCoreHypervisorServiceServer) testEmbeddedByValue()                               {}

// UnsafeCoreHypervisorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreHypervisorServiceServer will
// result in compilation errors.
type UnsafeCoreHypervisorServiceServer interface {
	mustEmbedUnimplementedCoreHypervisorServiceServer()
}

func RegisterCoreHypervisorServiceServer(s grpc.ServiceRegistrar, srv CoreHypervisorServiceServer) {
	// If the following call pancis, it indicates UnimplementedCoreHypervisorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoreHypervisorService_ServiceDesc, srv)
}

func _CoreHypervisorService_GetHypervisorInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHypervisorInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreHypervisorServiceServer).GetHypervisorInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreHypervisorService_GetHypervisorInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreHypervisorServiceServer).GetHypervisorInfo(ctx, req.(*GetHypervisorInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoreHypervisorService_ServiceDesc is the grpc.ServiceDesc for CoreHypervisorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreHypervisorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CoreHypervisorService",
	HandlerType: (*CoreHypervisorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHypervisorInfo",
			Handler:    _CoreHypervisorService_GetHypervisorInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vm.proto",
}

const (
	VMService_StartVM_FullMethodName   = "/proto.VMService/StartVM"
	VMService_StopVM_FullMethodName    = "/proto.VMService/StopVM"
	VMService_GetVMInfo_FullMethodName = "/proto.VMService/GetVMInfo"
	VMService_PauseVM_FullMethodName   = "/proto.VMService/PauseVM"
	VMService_ResumeVM_FullMethodName  = "/proto.VMService/ResumeVM"
)

// VMServiceClient is the client API for VMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VMService provides methods to manage virtual machines.
type VMServiceClient interface {
	// StartVM starts a virtual machine based on the provided configuration.
	StartVM(ctx context.Context, in *StartVMRequest, opts ...grpc.CallOption) (*StartVMResponse, error)
	// StopVM stops a running virtual machine.
	StopVM(ctx context.Context, in *StopVMRequest, opts ...grpc.CallOption) (*StopVMResponse, error)
	// GetVMInfo retrieves information about a specific VM.
	GetVMInfo(ctx context.Context, in *GetVMInfoRequest, opts ...grpc.CallOption) (*GetVMInfoResponse, error)
	// PauseVM pauses a running virtual machine.
	PauseVM(ctx context.Context, in *PauseVMRequest, opts ...grpc.CallOption) (*PauseVMResponse, error)
	// ResumeVM resumes a paused virtual machine.
	ResumeVM(ctx context.Context, in *ResumeVMRequest, opts ...grpc.CallOption) (*ResumeVMResponse, error)
}

type vMServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVMServiceClient(cc grpc.ClientConnInterface) VMServiceClient {
	return &vMServiceClient{cc}
}

func (c *vMServiceClient) StartVM(ctx context.Context, in *StartVMRequest, opts ...grpc.CallOption) (*StartVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartVMResponse)
	err := c.cc.Invoke(ctx, VMService_StartVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) StopVM(ctx context.Context, in *StopVMRequest, opts ...grpc.CallOption) (*StopVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopVMResponse)
	err := c.cc.Invoke(ctx, VMService_StopVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) GetVMInfo(ctx context.Context, in *GetVMInfoRequest, opts ...grpc.CallOption) (*GetVMInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVMInfoResponse)
	err := c.cc.Invoke(ctx, VMService_GetVMInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) PauseVM(ctx context.Context, in *PauseVMRequest, opts ...grpc.CallOption) (*PauseVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PauseVMResponse)
	err := c.cc.Invoke(ctx, VMService_PauseVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) ResumeVM(ctx context.Context, in *ResumeVMRequest, opts ...grpc.CallOption) (*ResumeVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeVMResponse)
	err := c.cc.Invoke(ctx, VMService_ResumeVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VMServiceServer is the server API for VMService service.
// All implementations must embed UnimplementedVMServiceServer
// for forward compatibility.
//
// VMService provides methods to manage virtual machines.
type VMServiceServer interface {
	// StartVM starts a virtual machine based on the provided configuration.
	StartVM(context.Context, *StartVMRequest) (*StartVMResponse, error)
	// StopVM stops a running virtual machine.
	StopVM(context.Context, *StopVMRequest) (*StopVMResponse, error)
	// GetVMInfo retrieves information about a specific VM.
	GetVMInfo(context.Context, *GetVMInfoRequest) (*GetVMInfoResponse, error)
	// PauseVM pauses a running virtual machine.
	PauseVM(context.Context, *PauseVMRequest) (*PauseVMResponse, error)
	// ResumeVM resumes a paused virtual machine.
	ResumeVM(context.Context, *ResumeVMRequest) (*ResumeVMResponse, error)
	mustEmbedUnimplementedVMServiceServer()
}

// UnimplementedVMServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVMServiceServer struct{}

func (UnimplementedVMServiceServer) StartVM(context.Context, *StartVMRequest) (*StartVMResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartVM not implemented")
}
func (UnimplementedVMServiceServer) StopVM(context.Context, *StopVMRequest) (*StopVMResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopVM not implemented")
}
func (UnimplementedVMServiceServer) GetVMInfo(context.Context, *GetVMInfoRequest) (*GetVMInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVMInfo not implemented")
}
func (UnimplementedVMServiceServer) PauseVM(context.Context, *PauseVMRequest) (*PauseVMResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PauseVM not implemented")
}
func (UnimplementedVMServiceServer) ResumeVM(context.Context, *ResumeVMRequest) (*ResumeVMResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeVM not implemented")
}
func (UnimplementedVMServiceServer) mustEmbedUnimplementedVMServiceServer() {}
func (UnimplementedVMServiceServer) testEmbeddedByValue()                   {}

// UnsafeVMServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VMServiceServer will
// result in compilation errors.
type UnsafeVMServiceServer interface {
	mustEmbedUnimplementedVMServiceServer()
}

func RegisterVMServiceServer(s grpc.ServiceRegistrar, srv VMServiceServer) {
	// If the following call pancis, it indicates UnimplementedVMServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VMService_ServiceDesc, srv)
}

func _VMService_StartVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).StartVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_StartVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).StartVM(ctx, req.(*StartVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_StopVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).StopVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_StopVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).StopVM(ctx, req.(*StopVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_GetVMInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVMInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).GetVMInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_GetVMInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).GetVMInfo(ctx, req.(*GetVMInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_PauseVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).PauseVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_PauseVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).PauseVM(ctx, req.(*PauseVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_ResumeVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).ResumeVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_ResumeVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).ResumeVM(ctx, req.(*ResumeVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VMService_ServiceDesc is the grpc.ServiceDesc for VMService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VMService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.VMService",
	HandlerType: (*VMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartVM",
			Handler:    _VMService_StartVM_Handler,
		},
		{
			MethodName: "StopVM",
			Handler:    _VMService_StopVM_Handler,
		},
		{
			MethodName: "GetVMInfo",
			Handler:    _VMService_GetVMInfo_Handler,
		},
		{
			MethodName: "PauseVM",
			Handler:    _VMService_PauseVM_Handler,
		},
		{
			MethodName: "ResumeVM",
			Handler:    _VMService_ResumeVM_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vm.proto",
}
