// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: v_architect_core.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum for Virtual Hardware Architecture
type VirtualHardwareArch int32

const (
	VirtualHardwareArch_ARCH_UNSPECIFIED VirtualHardwareArch = 0
	VirtualHardwareArch_X86_64           VirtualHardwareArch = 1
	VirtualHardwareArch_ARM64            VirtualHardwareArch = 2
)

// Enum value maps for VirtualHardwareArch.
var (
	VirtualHardwareArch_name = map[int32]string{
		0: "ARCH_UNSPECIFIED",
		1: "X86_64",
		2: "ARM64",
	}
	VirtualHardwareArch_value = map[string]int32{
		"ARCH_UNSPECIFIED": 0,
		"X86_64":           1,
		"ARM64":            2,
	}
)

func (x VirtualHardwareArch) Enum() *VirtualHardwareArch {
	p := new(VirtualHardwareArch)
	*p = x
	return p
}

func (x VirtualHardwareArch) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VirtualHardwareArch) Descriptor() protoreflect.EnumDescriptor {
	return file_v_architect_core_proto_enumTypes[0].Descriptor()
}

func (VirtualHardwareArch) Type() protoreflect.EnumType {
	return &file_v_architect_core_proto_enumTypes[0]
}

func (x VirtualHardwareArch) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VirtualHardwareArch.Descriptor instead.
func (VirtualHardwareArch) EnumDescriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{0}
}

type SerialPortConfig_SerialPortBackendType int32

const (
	SerialPortConfig_SERIAL_BACKEND_UNSPECIFIED SerialPortConfig_SerialPortBackendType = 0
	SerialPortConfig_STDIO                      SerialPortConfig_SerialPortBackendType = 1 // Connect to VMM's stdio
	SerialPortConfig_FILE                       SerialPortConfig_SerialPortBackendType = 2 // Output to a host file
	SerialPortConfig_PTY                        SerialPortConfig_SerialPortBackendType = 3 // Create a pseudo-terminal on the host
)

// Enum value maps for SerialPortConfig_SerialPortBackendType.
var (
	SerialPortConfig_SerialPortBackendType_name = map[int32]string{
		0: "SERIAL_BACKEND_UNSPECIFIED",
		1: "STDIO",
		2: "FILE",
		3: "PTY",
	}
	SerialPortConfig_SerialPortBackendType_value = map[string]int32{
		"SERIAL_BACKEND_UNSPECIFIED": 0,
		"STDIO":                      1,
		"FILE":                       2,
		"PTY":                        3,
	}
)

func (x SerialPortConfig_SerialPortBackendType) Enum() *SerialPortConfig_SerialPortBackendType {
	p := new(SerialPortConfig_SerialPortBackendType)
	*p = x
	return p
}

func (x SerialPortConfig_SerialPortBackendType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SerialPortConfig_SerialPortBackendType) Descriptor() protoreflect.EnumDescriptor {
	return file_v_architect_core_proto_enumTypes[1].Descriptor()
}

func (SerialPortConfig_SerialPortBackendType) Type() protoreflect.EnumType {
	return &file_v_architect_core_proto_enumTypes[1]
}

func (x SerialPortConfig_SerialPortBackendType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SerialPortConfig_SerialPortBackendType.Descriptor instead.
func (SerialPortConfig_SerialPortBackendType) EnumDescriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{2, 0}
}

// Nested message for DiskImage
type DiskImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"` // e.g., "qcow2", "raw"
	ReadOnly      bool                   `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskImage) Reset() {
	*x = DiskImage{}
	mi := &file_v_architect_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskImage) ProtoMessage() {}

func (x *DiskImage) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskImage.ProtoReflect.Descriptor instead.
func (*DiskImage) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{0}
}

func (x *DiskImage) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DiskImage) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *DiskImage) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

// Nested message for NetworkInterface
type NetworkInterface struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                               // e.g., "virtio-net"
	MacAddress    string                 `protobuf:"bytes,2,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"` // Optional, can be auto-generated
	BridgeName    string                 `protobuf:"bytes,3,opt,name=bridge_name,json=bridgeName,proto3" json:"bridge_name,omitempty"` // Host bridge to attach to
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInterface) Reset() {
	*x = NetworkInterface{}
	mi := &file_v_architect_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInterface) ProtoMessage() {}

func (x *NetworkInterface) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInterface.ProtoReflect.Descriptor instead.
func (*NetworkInterface) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{1}
}

func (x *NetworkInterface) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NetworkInterface) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *NetworkInterface) GetBridgeName() string {
	if x != nil {
		return x.BridgeName
	}
	return ""
}

// Nested message for SerialPortConfig
type SerialPortConfig struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Type          SerialPortConfig_SerialPortBackendType `protobuf:"varint,1,opt,name=type,proto3,enum=proto.SerialPortConfig_SerialPortBackendType" json:"type,omitempty"`
	PathIfFile    string                                 `protobuf:"bytes,2,opt,name=path_if_file,json=pathIfFile,proto3" json:"path_if_file,omitempty"` // Path on host if type is FILE
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SerialPortConfig) Reset() {
	*x = SerialPortConfig{}
	mi := &file_v_architect_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerialPortConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerialPortConfig) ProtoMessage() {}

func (x *SerialPortConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerialPortConfig.ProtoReflect.Descriptor instead.
func (*SerialPortConfig) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{2}
}

func (x *SerialPortConfig) GetType() SerialPortConfig_SerialPortBackendType {
	if x != nil {
		return x.Type
	}
	return SerialPortConfig_SERIAL_BACKEND_UNSPECIFIED
}

func (x *SerialPortConfig) GetPathIfFile() string {
	if x != nil {
		return x.PathIfFile
	}
	return ""
}

// Simplified VCPUConfig
type VCPUConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnableKvmHv   bool                   `protobuf:"varint,1,opt,name=enable_kvm_hv,json=enableKvmHv,proto3" json:"enable_kvm_hv,omitempty"` // Hint to enable KVM hardware virtualization
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VCPUConfig) Reset() {
	*x = VCPUConfig{}
	mi := &file_v_architect_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VCPUConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VCPUConfig) ProtoMessage() {}

func (x *VCPUConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VCPUConfig.ProtoReflect.Descriptor instead.
func (*VCPUConfig) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{3}
}

func (x *VCPUConfig) GetEnableKvmHv() bool {
	if x != nil {
		return x.EnableKvmHv
	}
	return false
}

// Simplified MemoryConfig
type MemoryConfig struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	EnableHugePages     bool                   `protobuf:"varint,1,opt,name=enable_huge_pages,json=enableHugePages,proto3" json:"enable_huge_pages,omitempty"`
	EnableMemBallooning bool                   `protobuf:"varint,2,opt,name=enable_mem_ballooning,json=enableMemBallooning,proto3" json:"enable_mem_ballooning,omitempty"` // For VirtIO balloon device
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MemoryConfig) Reset() {
	*x = MemoryConfig{}
	mi := &file_v_architect_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryConfig) ProtoMessage() {}

func (x *MemoryConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryConfig.ProtoReflect.Descriptor instead.
func (*MemoryConfig) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{4}
}

func (x *MemoryConfig) GetEnableHugePages() bool {
	if x != nil {
		return x.EnableHugePages
	}
	return false
}

func (x *MemoryConfig) GetEnableMemBallooning() bool {
	if x != nil {
		return x.EnableMemBallooning
	}
	return false
}

// Placeholder AIHardwareConfig
type AIHardwareConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnableAiCpu   bool                   `protobuf:"varint,1,opt,name=enable_ai_cpu,json=enableAiCpu,proto3" json:"enable_ai_cpu,omitempty"` // e.g., virtual NPU/TPU
	EnableAiGpu   bool                   `protobuf:"varint,2,opt,name=enable_ai_gpu,json=enableAiGpu,proto3" json:"enable_ai_gpu,omitempty"` // e.g., virtual AI-optimized GPU
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIHardwareConfig) Reset() {
	*x = AIHardwareConfig{}
	mi := &file_v_architect_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIHardwareConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIHardwareConfig) ProtoMessage() {}

func (x *AIHardwareConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIHardwareConfig.ProtoReflect.Descriptor instead.
func (*AIHardwareConfig) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{5}
}

func (x *AIHardwareConfig) GetEnableAiCpu() bool {
	if x != nil {
		return x.EnableAiCpu
	}
	return false
}

func (x *AIHardwareConfig) GetEnableAiGpu() bool {
	if x != nil {
		return x.EnableAiGpu
	}
	return false
}

// Main VM Configuration message
type VMConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	VmId              string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`                 // Unique ID (UUID recommended)
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                             // User-friendly name
	VcpuCores         uint32                 `protobuf:"varint,3,opt,name=vcpu_cores,json=vcpuCores,proto3" json:"vcpu_cores,omitempty"` // Total number of vCPU cores
	MemoryMb          uint64                 `protobuf:"varint,4,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`    // Total memory in Megabytes
	DiskImages        []*DiskImage           `protobuf:"bytes,5,rep,name=disk_images,json=diskImages,proto3" json:"disk_images,omitempty"`
	NetworkInterfaces []*NetworkInterface    `protobuf:"bytes,6,rep,name=network_interfaces,json=networkInterfaces,proto3" json:"network_interfaces,omitempty"`
	SerialPorts       []*SerialPortConfig    `protobuf:"bytes,7,rep,name=serial_ports,json=serialPorts,proto3" json:"serial_ports,omitempty"`
	EnableBiosBoot    bool                   `protobuf:"varint,8,opt,name=enable_bios_boot,json=enableBiosBoot,proto3" json:"enable_bios_boot,omitempty"`   // True for BIOS, false for UEFI (simplified)
	KernelImagePath   string                 `protobuf:"bytes,9,opt,name=kernel_image_path,json=kernelImagePath,proto3" json:"kernel_image_path,omitempty"` // Path to kernel image on host (for direct kernel boot)
	InitrdPath        string                 `protobuf:"bytes,10,opt,name=initrd_path,json=initrdPath,proto3" json:"initrd_path,omitempty"`                 // Path to initrd image on host (optional)
	KernelCmdline     string                 `protobuf:"bytes,11,opt,name=kernel_cmdline,json=kernelCmdline,proto3" json:"kernel_cmdline,omitempty"`        // Kernel command line parameters
	Arch              VirtualHardwareArch    `protobuf:"varint,12,opt,name=arch,proto3,enum=proto.VirtualHardwareArch" json:"arch,omitempty"`               // x86_64 or ARM64
	VcpuConfig        *VCPUConfig            `protobuf:"bytes,13,opt,name=vcpu_config,json=vcpuConfig,proto3" json:"vcpu_config,omitempty"`
	MemoryConfig      *MemoryConfig          `protobuf:"bytes,14,opt,name=memory_config,json=memoryConfig,proto3" json:"memory_config,omitempty"`
	AiHardwareConfig  *AIHardwareConfig      `protobuf:"bytes,15,opt,name=ai_hardware_config,json=aiHardwareConfig,proto3" json:"ai_hardware_config,omitempty"`                                 // Placeholder for future expansion
	Metadata          map[string]string      `protobuf:"bytes,16,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // For arbitrary key-value pairs
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VMConfig) Reset() {
	*x = VMConfig{}
	mi := &file_v_architect_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMConfig) ProtoMessage() {}

func (x *VMConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMConfig.ProtoReflect.Descriptor instead.
func (*VMConfig) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{6}
}

func (x *VMConfig) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *VMConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VMConfig) GetVcpuCores() uint32 {
	if x != nil {
		return x.VcpuCores
	}
	return 0
}

func (x *VMConfig) GetMemoryMb() uint64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *VMConfig) GetDiskImages() []*DiskImage {
	if x != nil {
		return x.DiskImages
	}
	return nil
}

func (x *VMConfig) GetNetworkInterfaces() []*NetworkInterface {
	if x != nil {
		return x.NetworkInterfaces
	}
	return nil
}

func (x *VMConfig) GetSerialPorts() []*SerialPortConfig {
	if x != nil {
		return x.SerialPorts
	}
	return nil
}

func (x *VMConfig) GetEnableBiosBoot() bool {
	if x != nil {
		return x.EnableBiosBoot
	}
	return false
}

func (x *VMConfig) GetKernelImagePath() string {
	if x != nil {
		return x.KernelImagePath
	}
	return ""
}

func (x *VMConfig) GetInitrdPath() string {
	if x != nil {
		return x.InitrdPath
	}
	return ""
}

func (x *VMConfig) GetKernelCmdline() string {
	if x != nil {
		return x.KernelCmdline
	}
	return ""
}

func (x *VMConfig) GetArch() VirtualHardwareArch {
	if x != nil {
		return x.Arch
	}
	return VirtualHardwareArch_ARCH_UNSPECIFIED
}

func (x *VMConfig) GetVcpuConfig() *VCPUConfig {
	if x != nil {
		return x.VcpuConfig
	}
	return nil
}

func (x *VMConfig) GetMemoryConfig() *MemoryConfig {
	if x != nil {
		return x.MemoryConfig
	}
	return nil
}

func (x *VMConfig) GetAiHardwareConfig() *AIHardwareConfig {
	if x != nil {
		return x.AiHardwareConfig
	}
	return nil
}

func (x *VMConfig) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// CoreHypervisorService Messages
type CreateVMRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Config         *VMConfig              `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	VmIdSuggestion string                 `protobuf:"bytes,2,opt,name=vm_id_suggestion,json=vmIdSuggestion,proto3" json:"vm_id_suggestion,omitempty"` // Optional: user can suggest an ID
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateVMRequest) Reset() {
	*x = CreateVMRequest{}
	mi := &file_v_architect_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVMRequest) ProtoMessage() {}

func (x *CreateVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVMRequest.ProtoReflect.Descriptor instead.
func (*CreateVMRequest) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{7}
}

func (x *CreateVMRequest) GetConfig() *VMConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CreateVMRequest) GetVmIdSuggestion() string {
	if x != nil {
		return x.VmIdSuggestion
	}
	return ""
}

type CreateVMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"` // Actual ID assigned (could be suggestion or generated)
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVMResponse) Reset() {
	*x = CreateVMResponse{}
	mi := &file_v_architect_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVMResponse) ProtoMessage() {}

func (x *CreateVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVMResponse.ProtoReflect.Descriptor instead.
func (*CreateVMResponse) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{8}
}

func (x *CreateVMResponse) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *CreateVMResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateVMResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// VMService Messages
type StartVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVMRequest) Reset() {
	*x = StartVMRequest{}
	mi := &file_v_architect_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVMRequest) ProtoMessage() {}

func (x *StartVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVMRequest.ProtoReflect.Descriptor instead.
func (*StartVMRequest) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{9}
}

func (x *StartVMRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type StartVMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVMResponse) Reset() {
	*x = StartVMResponse{}
	mi := &file_v_architect_core_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVMResponse) ProtoMessage() {}

func (x *StartVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVMResponse.ProtoReflect.Descriptor instead.
func (*StartVMResponse) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{10}
}

func (x *StartVMResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartVMResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StopVMRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VmId           string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Force          bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`                                         // True for immediate power-off, false for graceful shutdown
	TimeoutSeconds uint32                 `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"` // Timeout for graceful shutdown
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StopVMRequest) Reset() {
	*x = StopVMRequest{}
	mi := &file_v_architect_core_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVMRequest) ProtoMessage() {}

func (x *StopVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopVMRequest.ProtoReflect.Descriptor instead.
func (*StopVMRequest) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{11}
}

func (x *StopVMRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *StopVMRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *StopVMRequest) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type StopVMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopVMResponse) Reset() {
	*x = StopVMResponse{}
	mi := &file_v_architect_core_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVMResponse) ProtoMessage() {}

func (x *StopVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v_architect_core_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopVMResponse.ProtoReflect.Descriptor instead.
func (*StopVMResponse) Descriptor() ([]byte, []int) {
	return file_v_architect_core_proto_rawDescGZIP(), []int{12}
}

func (x *StopVMResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopVMResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_v_architect_core_proto protoreflect.FileDescriptor

const file_v_architect_core_proto_rawDesc = "" +
	"\n" +
	"\x16v_architect_core.proto\x12\x05proto\"T\n" +
	"\tDiskImage\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x1b\n" +
	"\tread_only\x18\x03 \x01(\bR\breadOnly\"h\n" +
	"\x10NetworkInterface\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1f\n" +
	"\vmac_address\x18\x02 \x01(\tR\n" +
	"macAddress\x12\x1f\n" +
	"\vbridge_name\x18\x03 \x01(\tR\n" +
	"bridgeName\"\xce\x01\n" +
	"\x10SerialPortConfig\x12A\n" +
	"\x04type\x18\x01 \x01(\x0e2-.proto.SerialPortConfig.SerialPortBackendTypeR\x04type\x12 \n" +
	"\fpath_if_file\x18\x02 \x01(\tR\n" +
	"pathIfFile\"U\n" +
	"\x15SerialPortBackendType\x12\x1e\n" +
	"\x1aSERIAL_BACKEND_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05STDIO\x10\x01\x12\b\n" +
	"\x04FILE\x10\x02\x12\a\n" +
	"\x03PTY\x10\x03\"0\n" +
	"\n" +
	"VCPUConfig\x12\"\n" +
	"\renable_kvm_hv\x18\x01 \x01(\bR\venableKvmHv\"n\n" +
	"\fMemoryConfig\x12*\n" +
	"\x11enable_huge_pages\x18\x01 \x01(\bR\x0fenableHugePages\x122\n" +
	"\x15enable_mem_ballooning\x18\x02 \x01(\bR\x13enableMemBallooning\"Z\n" +
	"\x10AIHardwareConfig\x12\"\n" +
	"\renable_ai_cpu\x18\x01 \x01(\bR\venableAiCpu\x12\"\n" +
	"\renable_ai_gpu\x18\x02 \x01(\bR\venableAiGpu\"\xa1\x06\n" +
	"\bVMConfig\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"vcpu_cores\x18\x03 \x01(\rR\tvcpuCores\x12\x1b\n" +
	"\tmemory_mb\x18\x04 \x01(\x04R\bmemoryMb\x121\n" +
	"\vdisk_images\x18\x05 \x03(\v2\x10.proto.DiskImageR\n" +
	"diskImages\x12F\n" +
	"\x12network_interfaces\x18\x06 \x03(\v2\x17.proto.NetworkInterfaceR\x11networkInterfaces\x12:\n" +
	"\fserial_ports\x18\a \x03(\v2\x17.proto.SerialPortConfigR\vserialPorts\x12(\n" +
	"\x10enable_bios_boot\x18\b \x01(\bR\x0eenableBiosBoot\x12*\n" +
	"\x11kernel_image_path\x18\t \x01(\tR\x0fkernelImagePath\x12\x1f\n" +
	"\vinitrd_path\x18\n" +
	" \x01(\tR\n" +
	"initrdPath\x12%\n" +
	"\x0ekernel_cmdline\x18\v \x01(\tR\rkernelCmdline\x12.\n" +
	"\x04arch\x18\f \x01(\x0e2\x1a.proto.VirtualHardwareArchR\x04arch\x122\n" +
	"\vvcpu_config\x18\r \x01(\v2\x11.proto.VCPUConfigR\n" +
	"vcpuConfig\x128\n" +
	"\rmemory_config\x18\x0e \x01(\v2\x13.proto.MemoryConfigR\fmemoryConfig\x12E\n" +
	"\x12ai_hardware_config\x18\x0f \x01(\v2\x17.proto.AIHardwareConfigR\x10aiHardwareConfig\x129\n" +
	"\bmetadata\x18\x10 \x03(\v2\x1d.proto.VMConfig.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"d\n" +
	"\x0fCreateVMRequest\x12'\n" +
	"\x06config\x18\x01 \x01(\v2\x0f.proto.VMConfigR\x06config\x12(\n" +
	"\x10vm_id_suggestion\x18\x02 \x01(\tR\x0evmIdSuggestion\"[\n" +
	"\x10CreateVMResponse\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"%\n" +
	"\x0eStartVMRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"E\n" +
	"\x0fStartVMResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"c\n" +
	"\rStopVMRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\rR\x0etimeoutSeconds\"D\n" +
	"\x0eStopVMResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*B\n" +
	"\x13VirtualHardwareArch\x12\x14\n" +
	"\x10ARCH_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06X86_64\x10\x01\x12\t\n" +
	"\x05ARM64\x10\x022T\n" +
	"\x15CoreHypervisorService\x12;\n" +
	"\bCreateVM\x12\x16.proto.CreateVMRequest\x1a\x17.proto.CreateVMResponse2|\n" +
	"\tVMService\x128\n" +
	"\aStartVM\x12\x15.proto.StartVMRequest\x1a\x16.proto.StartVMResponse\x125\n" +
	"\x06StopVM\x12\x14.proto.StopVMRequest\x1a\x15.proto.StopVMResponseB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_v_architect_core_proto_rawDescOnce sync.Once
	file_v_architect_core_proto_rawDescData []byte
)

func file_v_architect_core_proto_rawDescGZIP() []byte {
	file_v_architect_core_proto_rawDescOnce.Do(func() {
		file_v_architect_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v_architect_core_proto_rawDesc), len(file_v_architect_core_proto_rawDesc)))
	})
	return file_v_architect_core_proto_rawDescData
}

var file_v_architect_core_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_v_architect_core_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_v_architect_core_proto_goTypes = []any{
	(VirtualHardwareArch)(0),                    // 0: proto.VirtualHardwareArch
	(SerialPortConfig_SerialPortBackendType)(0), // 1: proto.SerialPortConfig.SerialPortBackendType
	(*DiskImage)(nil),                           // 2: proto.DiskImage
	(*NetworkInterface)(nil),                    // 3: proto.NetworkInterface
	(*SerialPortConfig)(nil),                    // 4: proto.SerialPortConfig
	(*VCPUConfig)(nil),                          // 5: proto.VCPUConfig
	(*MemoryConfig)(nil),                        // 6: proto.MemoryConfig
	(*AIHardwareConfig)(nil),                    // 7: proto.AIHardwareConfig
	(*VMConfig)(nil),                            // 8: proto.VMConfig
	(*CreateVMRequest)(nil),                     // 9: proto.CreateVMRequest
	(*CreateVMResponse)(nil),                    // 10: proto.CreateVMResponse
	(*StartVMRequest)(nil),                      // 11: proto.StartVMRequest
	(*StartVMResponse)(nil),                     // 12: proto.StartVMResponse
	(*StopVMRequest)(nil),                       // 13: proto.StopVMRequest
	(*StopVMResponse)(nil),                      // 14: proto.StopVMResponse
	nil,                                         // 15: proto.VMConfig.MetadataEntry
}
var file_v_architect_core_proto_depIdxs = []int32{
	1,  // 0: proto.SerialPortConfig.type:type_name -> proto.SerialPortConfig.SerialPortBackendType
	2,  // 1: proto.VMConfig.disk_images:type_name -> proto.DiskImage
	3,  // 2: proto.VMConfig.network_interfaces:type_name -> proto.NetworkInterface
	4,  // 3: proto.VMConfig.serial_ports:type_name -> proto.SerialPortConfig
	0,  // 4: proto.VMConfig.arch:type_name -> proto.VirtualHardwareArch
	5,  // 5: proto.VMConfig.vcpu_config:type_name -> proto.VCPUConfig
	6,  // 6: proto.VMConfig.memory_config:type_name -> proto.MemoryConfig
	7,  // 7: proto.VMConfig.ai_hardware_config:type_name -> proto.AIHardwareConfig
	15, // 8: proto.VMConfig.metadata:type_name -> proto.VMConfig.MetadataEntry
	8,  // 9: proto.CreateVMRequest.config:type_name -> proto.VMConfig
	9,  // 10: proto.CoreHypervisorService.CreateVM:input_type -> proto.CreateVMRequest
	11, // 11: proto.VMService.StartVM:input_type -> proto.StartVMRequest
	13, // 12: proto.VMService.StopVM:input_type -> proto.StopVMRequest
	10, // 13: proto.CoreHypervisorService.CreateVM:output_type -> proto.CreateVMResponse
	12, // 14: proto.VMService.StartVM:output_type -> proto.StartVMResponse
	14, // 15: proto.VMService.StopVM:output_type -> proto.StopVMResponse
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_v_architect_core_proto_init() }
func file_v_architect_core_proto_init() {
	if File_v_architect_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v_architect_core_proto_rawDesc), len(file_v_architect_core_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_v_architect_core_proto_goTypes,
		DependencyIndexes: file_v_architect_core_proto_depIdxs,
		EnumInfos:         file_v_architect_core_proto_enumTypes,
		MessageInfos:      file_v_architect_core_proto_msgTypes,
	}.Build()
	File_v_architect_core_proto = out.File
	file_v_architect_core_proto_goTypes = nil
	file_v_architect_core_proto_depIdxs = nil
}
